railroad-ebnf-beta
title "Top level DSL factory DSL"

top-level = { parserSpecificationClause
            | keywordsClause
            | operatorsClause
            | expressionClause
            | arbitraryTokenClause
            | defineSequentialClause
            | defineSwitchClause
            | switchClause } ;
